'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ArrowLeft,Check,ChevronRight,ClipboardCheck,MapPin,Navigation,Route,ShieldAlert,Timer } from 'lucide-react';
import { Button } from '@/components/ui/button';
type Assignment={id:string;routeId:string;stopOrder:number;status:string;reportId:string;title:string;address:string;description:string;severity:string;latitude:number;longitude:number};
export function InspectorPortal(){
 const [items,setItems]=useState<Assignment[]>([]);const [selected,setSelected]=useState<Assignment|null>(null);const [message,setMessage]=useState('');
 async function load(){const data=await fetch('/api/assignments?inspectorId=FIELD-TEAM-01').then(async r=>await r.json() as {assignments:Assignment[]});setItems(data.assignments??[]);setSelected((current)=>current??data.assignments?.[0]??null)}useEffect(()=>{let cancelled=false;void fetch('/api/assignments?inspectorId=FIELD-TEAM-01').then(async r=>await r.json() as {assignments:Assignment[]}).then((data)=>{if(!cancelled){setItems(data.assignments??[]);setSelected(data.assignments?.[0]??null)}});return()=>{cancelled=true}},[]);
 async function update(status:string){if(!selected)return;const response=await fetch(`/api/reports/${selected.reportId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,note:message||`Updated by field inspector from assignment ${selected.id}.`})});if(response.ok){setMessage('');await load();setSelected((current)=>current?{...current,status}:current)}}
 return <main className="inspector-page"><header className="inspector-top"><Link href="/" className="back-link"><ArrowLeft/> Operations</Link><div className="inspector-identity"><div>01</div><span><strong>Field Team 01</strong><small>Inspector workspace · Motorbike</small></span></div></header>
 <section className="inspector-banner"><div><div className="eyebrow"><ClipboardCheck/> Field workspace</div><h1>Field assignments</h1><p>{items.length?`This team has ${items.length} priority stops assigned.`:'No active route is assigned yet.'}</p></div><div className="route-summary"><Route/><span><strong>{items[0]?.routeId?.slice(0,18)??'Waiting for route'}</strong><small>Live route · Operations can replan</small></span></div></section>
 <div className="inspector-layout"><aside className="stop-list"><div className="stop-heading"><span>Today’s route</span><strong>{items.length} stops</strong></div>{items.length===0?<div className="empty-route">Assignments approved in operations will appear here instantly.</div>:items.map((item)=><button key={item.id} onClick={()=>setSelected(item)} className={selected?.id===item.id?'active':''}><i>{item.stopOrder}</i><span><strong>{item.title}</strong><small>{item.address}</small></span><ChevronRight/></button>)}</aside>
 <section className="inspection-card">{selected?<><div className="inspection-head"><div><span className={`status-chip ${selected.severity}`}>{selected.severity}</span><small>{selected.reportId}</small></div><h2>{selected.title}</h2><p><MapPin/> {selected.address}</p></div><div className="inspection-body"><div className="evidence-box"><span>Resident evidence</span><p>{selected.description}</p></div><div className="field-map"><i><MapPin/></i><span>Live incident location</span><a href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}`} target="_blank" rel="noreferrer"><Navigation/> Open navigation</a></div><label>Inspection note<textarea value={message} onChange={(e)=>setMessage(e.target.value)} placeholder="Record what you observed and any work completed."/></label><div className="inspection-actions"><Button variant="outline" onClick={()=>update('reopened')}><ShieldAlert/> Mark blocked</Button><Button variant="outline" onClick={()=>update('inspecting')}><Timer/> Start inspection</Button><Button onClick={()=>update('resolved')}><Check/> Resolve report</Button></div></div></>:<div className="empty-route">Select an assigned stop to begin.</div>}</section></div></main>
}
